# https://circleci.com/docs/2.0/language-javascript/
version: 2
jobs:
  'node-10':
    docker:
      - image: circleci/node:10
    working_directory: ~/omo-quantum
    steps:
      - checkout

      # Download and cache dependencies
      - restore_cache:
          keys:
            - v1-dependencies-{{ checksum "package.json" }}
            # fallback to using the latest cache if no exact match is found
            - v1-dependencies-

      - run: npm install

      - save_cache:
          paths:
            - node_modules
          key: v1-dependencies-{{ checksum "package.json" }}
      - run: npm test
      - run: npm run cov:send
      - run: npm run cov:check

      # - deploy:
      #     name: Deploy Over SSH
      #     command: |
      #       ssh -o StrictHostKeyChecking=no $SSH_USER@$SSH_HOST exit
      #       scp -r ~/repo/dist/* $SSH_USER@$SSH_HOST:$DEPLOY_PATH

  'node-latest':
    docker:
      - image: circleci/node:latest
    working_directory: ~/omo-quantum
    steps:
      - checkout
      - restore_cache:
          keys:
            - v1-dependencies-{{ checksum "package.json" }}
            - v1-dependencies-
      - run: npm install
      - save_cache:
          paths:
            - node_modules
          key: v1-dependencies-{{ checksum "package.json" }}
      - run: npm test
      - run: npm run cov:send
      - run: npm run cov:check

workflows:
  version: 2
  build:
    jobs:
      - 'node-10'
      - 'node-latest'
