import { SchemaTypes } from "../../../../../_generated/schemaTypes";

/* tslint:disable */
/**
 * This file was automatically generated by json-schema-to-typescript.
 * DO NOT MODIFY IT BY HAND. Instead, modify the source JSONSchema file,
 * and run json-schema-to-typescript to regenerate this file.
 */

/**
 * Contains the json web token and owner agent id
 */
export interface Session_1_0_0 {
   _$schemaId: SchemaTypes.Session_1_0_0;

  id: number;
  jwt: string;
  userId: number;
  timezoneOffset?: number;
  validTo?: string;
  createdAt?: string;
  [k: string]: unknown;
}
