name: "Deploy Dev"
on:
  push:
    branches:
      - dev
  pull_request:
    branches:
      - dev

jobs:
  bucket_push:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [12.x]

    name: push textile bucket
    steps:
      - uses: actions/checkout@v2
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v1
        with:
          node-version: ${{ matrix.node-version }}
      - run: cd app
      - run: ls

      - name: push action
        id: bucket
        uses: textileio/github-action-buckets@master
        with:
          key: ${{ secrets.TEXTILE_ACCOUNT_KEY }}
          secret: ${{ secrets.TEXTILE_ACCOUNT_SECRET }}
          bucket: "dev"
          thread: "bafkzzpucn72mnmzuxhdf7bjqgi6nlodfsaxncorz6piecpwx3thgmhi"
          path: "public"
