name: "Textile Bucket - Deploy to alpha.omo.earth"
on:
  push:
    branches:
      - alpha
  pull_request:
    branches:
      - alpha

jobs:
  bucket_push:
    runs-on: ubuntu-latest
    name: push textile bucket
    steps:
      - name: push action
        id: bucket
        uses: textileio/github-action-buckets@master
        with:
          key: ${{ secrets.TEXTILE_ACCOUNT_KEY }}
          secret: ${{ secrets.TEXTILE_ACCOUNT_SECRET }}
          bucket: "omoalpha"
          thread: "bafk7mhggozfex3ntnpydu455yvxfa7glos2uebofmukk5tmepl6klaq"
          path: "public/"
