name: "Deploy Dev"
on:
  push:
    branches:
      - dev
  pull_request:
    branches:
      - dev

jobs:
  bucket_push:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [12.x]

    name: push textile bucket
    steps:
      - uses: actions/checkout@v2
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v1
        with:
          node-version: ${{ matrix.node-version }}

      - name: push action
        id: bucket
        uses: textileio/github-action-buckets@master
        with:
          key: ${{ secrets.TEXTILE_ACCOUNT_KEY }}
          secret: ${{ secrets.TEXTILE_ACCOUNT_SECRET }}
          bucket: "dev"
          thread: "bafkzzpucn72mnmzuxhdf7bjqgi6nlodfsaxncorz6piecpwx3thgmhi"
          path: "app/public"
          pattern: "**/*"
      - run: echo "bucket - ${{ steps.bucket.outputs.key }}"
          - run: echo "ipfs - ${{ steps.bucket.outputs.ipfs }}"
          - run: echo "ipfs link - ${{ steps.bucket.outputs.ipfsUrl }}"
          - run: echo "ipns - ${{ steps.bucket.outputs.ipns }}"
          - run: echo "ipns link - ${{ steps.bucket.outputs.ipnsUrl }}"
          - run: echo "hub - ${{ steps.bucket.outputs.hub }}"
          - run: echo "www - ${{ steps.bucket.outputs.www }}"